### ISSUE TITLE
Onder artikel vorige/vorige bericht (idee van whatabouther vind ik mooi)

### ISSUE THREAD

**Issue by elenihoefsloot** [festen/wpblog#16]

**Comment by festen** [comment]
@elenihoefsloot Gaat het dan vooral om de 'related articles' zoals in de screenshot ?

![screen shot 2015-04-18 at 22 29 47](https://cloud.githubusercontent.com/assets/6270156/7217144/81fa7676-e61a-11e4-8ac1-a73ef73e089a.png)

**Comment by elenihoefsloot** [comment]
Of vorige/volgende artikel. Wat is beter denk je?

**Comment by festen** [comment]
Volgens mij is het nu zoals je wilt, als dat niet is moet je dit ticket maar opnieuw openen
